In [2]:
#Random number, means somethign that can  not be predicted logically
#Pseudo random-random numbers generated through a generation algorithim
#Truly random-we need to get the random data from some outside source like mouse movements.Truly random are not needed, unless its related to security, encryption

# Generate Random Number

In [5]:
#Random module
from numpy import random
x = random.randint(100)
print(x)

42


In [6]:
y = random.rand()
print(y)

0.49463056245044235


random float

In [7]:
z = random.randint(100, size = (5))
print(z)

[70 82 25 48 64]


random Array, with size parameter

In [12]:
z = random.randint(100, size = (3, 5))#rows, columns
print(z)

[[63 63 69 86 12]
 [31 17 81 86 45]
 [20 58 32 14 45]]


In [15]:
a = random.randint(100, size = (5, 2))
print(a)

[[ 0 54]
 [64  9]
 [97 16]
 [60  9]
 [26 35]]


In [16]:
b = random.rand(5)
print(b)

[0.6718451  0.51944896 0.64614156 0.82337257 0.55720844]


In [18]:
x = random.randint(100)
print(x)

22


In [19]:
y = random.rand()
print(y)

0.13900082199719255


In [22]:
y = random.randint(3)
print(y)

2


In [23]:
x = random.rand(3, 5)
print(x)

[[0.91410902 0.12666542 0.96620248 0.84911899 0.22301924]
 [0.41952159 0.6194503  0.91081925 0.99539085 0.43529811]
 [0.54554368 0.17290994 0.49160395 0.02969794 0.54274556]]


generate 2D array, with 3 rows and 5 columns

# Random number from Array

In [26]:
from numpy import random
x = random.choice([3, 5, 7, 9])
x

9

In [28]:
#using choice method
x = random.choice([3, 5, 7, 9], size = (3, 5))
print(x)

[[9 9 5 5 7]
 [5 7 3 9 7]
 [5 3 9 5 9]]


# Random data Distribution

Data distribution; list of possible values, and how often each value occurs

Random distribution; is a set of random numbers that follow a certain probability density function

In [35]:
from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size = (100))
print(x)
#P, is the probability for the value of each number respectively

[7 7 7 7 7 5 7 7 5 5 5 7 7 5 7 7 5 7 7 5 7 7 5 7 7 5 7 3 3 7 3 5 7 7 7 3 7
 5 7 5 7 7 7 5 3 7 5 3 7 5 7 5 5 5 7 7 5 5 7 7 7 7 7 7 7 7 5 7 5 3 3 7 5 7
 7 5 5 7 7 5 7 7 7 7 7 7 7 5 7 5 3 7 7 7 5 7 7 7 5 5]


In [34]:
x = random.choice([3, 5, 7, 9], size = 100)
print(x)

[3 9 9 9 5 3 3 3 9 9 9 7 9 9 9 3 5 3 9 9 3 9 7 3 5 3 3 9 7 9 9 3 3 7 9 3 5
 7 7 3 7 9 7 5 5 7 7 3 5 5 5 7 9 7 7 3 9 3 5 5 7 7 3 5 3 7 7 3 5 9 7 3 5 5
 5 9 3 5 9 3 9 5 7 7 9 7 5 9 3 9 3 9 3 9 5 9 5 5 5 3]


sum of probability of all number should be 1

In [40]:
from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.4, 0.2], size = (100))
print(x)
#P, is the probability for the value of each number respectively

[3 7 7 9 7 5 7 5 3 9 3 3 9 7 7 5 5 7 7 9 5 5 5 9 9 9 9 9 9 5 7 7 5 9 5 7 5
 9 7 7 7 5 7 5 7 7 7 7 7 5 7 5 9 9 7 7 7 5 5 7 5 5 7 9 7 5 5 7 5 9 3 7 5 7
 5 7 5 5 9 3 3 5 7 5 5 5 7 9 5 9 9 7 7 5 9 9 7 5 5 5]


In [41]:
from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size = (3, 5))
print(x)

[[7 5 5 5 3]
 [7 7 7 7 7]
 [7 7 5 7 5]]


# Random permutations

Permutation;refers to an arrangement of Elements

SHUFFLING ARRAYS, changing arrangement of elements in the array itself

In [50]:
import numpy as np
from numpy import random
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)

[2 3 1 4 5]


In [52]:
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))

[2 5 3 1 4]
